name: Setup Git Settings
description: Composite GitHub Action to configure Git to sign commits with Bonita CI technical user
author: Bonitasoft

inputs:
  keeper-secret-config:
    description: The Keeper Secret Manager configuration
    required: true

outputs:
  fingerprint:
    description: Fingerprint of the GPG key used to sign commits
    value: ${{ steps.import-gpg.outputs.fingerprint }}
  name:
    description: Name associated with the GPG key used to sign commits
    value: ${{ steps.import-gpg.outputs.name }}
  email:
    description: Email address associated with the GPG key used to sign commits
    value: ${{ steps.import-gpg.outputs.email }}

runs:
  using: composite
  steps:
    - name: Retrieve GPG secrets from Keeper
      uses: Keeper-Security/ksm-action@v1
      with:
        keeper-secret-config: ${{ inputs.keeper-secret-config }}
        secrets: |
          kE5H6L68vUluOHvClGRl9A/custom_field/gpg-private-key > env:GPG_PRIVATE_KEY
          kE5H6L68vUluOHvClGRl9A/custom_field/gpg-passphrase > env:GPG_PASSPHRASE

    # The action below automatically set commit author's name and email
    # with those associated to the GPG key
    - name: Import GPG key
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
        passphrase: ${{ env.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_tag_gpgsign: true
