name: Setup Git Settings
description: Composite GitHub Action to configure Git to sign commits with CI technical user
inputs:
  keeper-secret-config:
    description: The Keeper Secret Manager configuration
    required: true

runs:
  using: composite
  steps:
    - name: Retrieve Artifactory secrets from Keeper
      uses: Keeper-Security/ksm-action@master
      with:
        keeper-secret-config: ${{ inputs.keeper-secret-config }}
        secrets: |
          kE5H6L68vUluOHvClGRl9A/custom_field/gpg-private-key > env.GPG_PRIVATE_KEY
          kE5H6L68vUluOHvClGRl9A/custom_field/gpg-passphrase > env.GPG_PASSPHRASE

    # commit author's name and email are set automatically with those associated to GPG key
    - name: Import GPG key
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
        passphrase: ${{ env.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_tag_gpgsign: true

    - name: GPG user IDs
      shell: bash
      run: |
        echo "fingerprint: ${{ steps.import-gpg.outputs.fingerprint }}"
        echo "keyid:       ${{ steps.import-gpg.outputs.keyid }}"
        echo "name:        ${{ steps.import-gpg.outputs.name }}"
        echo "email:       ${{ steps.import-gpg.outputs.email }}"
