name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Create dummy file
        run: |
          echo 'Hello World' > test-file.txt

      - name: Execute local action
        uses: ./
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - name: Test verified commit
        run: |
          git add .
          git commit -m "Test verified commit"
          git verify-commit HEAD
