name: Release new action version

run-name: Release version ${{ github.event.inputs.tag-name || github.event.release.tag_name }}

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag-name:
        description: "Tag name that the major tag will point to (e.g. v1.0.0)"
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.tag-name || github.event.release.tag_name }}

permissions:
  contents: write

jobs:
  release-action:
    runs-on: ubuntu-latest
    steps:
      - name: Publish action ${{ env.TAG_NAME }}
        uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ env.TAG_NAME }}
